package ec.edu.ups.vistas;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erics
 */
public class TresEnRaya extends javax.swing.JFrame {

    /**
     * Creates new form TresEnRaya
     */
    public TresEnRaya() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        boton4 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        linea1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        linea2 = new javax.swing.JLabel();
        linea6 = new javax.swing.JPanel();
        linea3 = new javax.swing.JPanel();
        linea4 = new javax.swing.JPanel();
        linea5 = new javax.swing.JPanel();
        linea7 = new javax.swing.JPanel();
        linea8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        j0 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        j00 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel6.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 241, 98, 85));

        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 145, 98, 85));

        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 145, 98, 85));

        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 241, 98, 85));

        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 337, 98, 85));

        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 337, 98, 85));

        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 145, 98, 85));

        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 241, 98, 85));

        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 337, 98, 85));

        jLabel1.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        jLabel1.setText("Tres en Raya");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Pristina", 2, 48)); // NOI18N
        jLabel2.setText("Victorias");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 180, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel3.setText("X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 23, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel4.setText("O");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel5.setText("0");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 23, -1));

        linea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/dia1.png"))); // NOI18N
        getContentPane().add(linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel7.setText("0");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 23, -1));

        linea2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/dia2.png"))); // NOI18N
        getContentPane().add(linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, -1, -1));

        linea6.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea6Layout = new javax.swing.GroupLayout(linea6);
        linea6.setLayout(linea6Layout);
        linea6Layout.setHorizontalGroup(
            linea6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        linea6Layout.setVerticalGroup(
            linea6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(linea6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 20));

        linea3.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea3Layout = new javax.swing.GroupLayout(linea3);
        linea3.setLayout(linea3Layout);
        linea3Layout.setHorizontalGroup(
            linea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        linea3Layout.setVerticalGroup(
            linea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(linea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 20, 280));

        linea4.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea4Layout = new javax.swing.GroupLayout(linea4);
        linea4.setLayout(linea4Layout);
        linea4Layout.setHorizontalGroup(
            linea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        linea4Layout.setVerticalGroup(
            linea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(linea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 20, 280));

        linea5.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea5Layout = new javax.swing.GroupLayout(linea5);
        linea5.setLayout(linea5Layout);
        linea5Layout.setHorizontalGroup(
            linea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        linea5Layout.setVerticalGroup(
            linea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(linea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 20, 280));

        linea7.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea7Layout = new javax.swing.GroupLayout(linea7);
        linea7.setLayout(linea7Layout);
        linea7Layout.setHorizontalGroup(
            linea7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        linea7Layout.setVerticalGroup(
            linea7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(linea7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 20));

        linea8.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout linea8Layout = new javax.swing.GroupLayout(linea8);
        linea8.setLayout(linea8Layout);
        linea8Layout.setHorizontalGroup(
            linea8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        linea8Layout.setVerticalGroup(
            linea8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(linea8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 310, 20));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Victorias");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        j0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jLabel8.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");

        javax.swing.GroupLayout j0Layout = new javax.swing.GroupLayout(j0);
        j0.setLayout(j0Layout);
        j0Layout.setHorizontalGroup(
            j0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j0Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        j0Layout.setVerticalGroup(
            j0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        j00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jLabel10.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("0");

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("O");

        javax.swing.GroupLayout j00Layout = new javax.swing.GroupLayout(j00);
        j00.setLayout(j00Layout);
        j00Layout.setHorizontalGroup(
            j00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j00Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j00Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        j00Layout.setVerticalGroup(
            j00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j00Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 200, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jButton1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jButton1.setText("Jugar de Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     //Iniciamos creando una matriz 
    private int matriz[][] = new int[3][3];

    //Creamos un metodo para ingresar los metodos
    public void ingresar() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                matriz[i][j] = (j + 10) * (i + 10);
            }
        }
    }

    Tres con = new Tres(0, 0, 0);
    //Metodo para desarrollar la opcion a elegir

    public void opcion() {
        if (con.getTurno() == 1) {
            j0.setBackground(Color.yellow);
            j00.setBackground(Color.green);
        }
        if (con.getTurno() == 0) {
            j0.setBackground(Color.green);
            j00.setBackground(Color.yellow);
        }
    }
    //Metodo para crear un nuevo juego

    public void nuevo() {
        ingresar();
        //Botones 1 a 9
        boton1.setText("");
        boton1.setEnabled(true);

        boton2.setText("");
        boton2.setEnabled(true);

        boton3.setText("");
        boton3.setEnabled(true);

        boton4.setText("");
        boton4.setEnabled(true);

        boton5.setText("");
        boton5.setEnabled(true);

        boton6.setText("");
        boton6.setEnabled(true);

        boton7.setText("");
        boton7.setEnabled(true);

        boton8.setText("");
        boton8.setEnabled(true);

        boton9.setText("");
        boton9.setEnabled(true);

        //lineas horizontales 
        linea6.setVisible(false);
        linea7.setVisible(false);
        linea8.setVisible(false);
        //lineas verticales
        linea3.setVisible(false);
        linea4.setVisible(false);
        linea5.setVisible(false);
        //lineas diagonales
        linea1.setVisible(false);
        linea2.setVisible(false);

    }
    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        opcion();
        //diagonal
        con.rayar(matriz, linea1, 7, 2, 2);
        //horizontal
        con.rayar(matriz, linea8, 3, 2, 2);
        //vertical
        con.rayar(matriz, linea3, 6, 2, 2);

        if (con.jugar(boton9, 2, 2, matriz, jLabel7, linea1) == 1) {

        }
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        opcion();
        //diagonal
        con.rayar(matriz, linea1, 7, 0, 0);
        //horizontal
        con.rayar(matriz, linea6, 1, 0, 0);
        //vertical
        con.rayar(matriz, linea3, 4, 0, 0);

        if (con.jugar(boton1, 0, 0, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        opcion();
        //horizontal
        con.rayar(matriz, linea6, 1, 0, 1);
        //vertical
        con.rayar(matriz, linea4, 5, 0, 1);

        if (con.jugar(boton2, 0, 1, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        opcion();
        //horizontal
        con.rayar(matriz, linea6, 1, 0, 2);
        //vertical
        con.rayar(matriz, linea5, 6, 0, 2);
        //diagonal
        con.rayar(matriz, linea8, 8, 0, 2);

        if (con.jugar(boton3, 0, 2, matriz, jLabel7, jLabel8) == 1) {
        }
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        opcion();
        //horizontal
        con.rayar(matriz, linea7, 2, 1, 0);
        //vertical
        con.rayar(matriz, linea3, 4, 1, 0);

        if (con.jugar(boton4, 1, 0, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        opcion();
        //diagonal
        con.rayar(matriz, linea1, 7, 1, 1);
        con.rayar(matriz, linea2, 8, 1, 1);
        //horizontal
        con.rayar(matriz, linea7, 2, 1, 1);
        //vertical
        con.rayar(matriz, linea4, 5, 1, 1);

        if (con.jugar(boton5, 1, 1, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        opcion();
        //horizontal
        con.rayar(matriz, linea7, 2, 1, 2);
        //vertical
        con.rayar(matriz, linea3, 6, 1, 2);

        if (con.jugar(boton6, 1, 02, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        con.rayar(matriz, linea8, 3, 2, 0);
        //vertical
        con.rayar(matriz, linea3, 4, 2, 0);
        //diagonal
        con.rayar(matriz, linea8, 8, 2, 0);

        if (con.jugar(boton7, 2, 0, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
         opcion();
        //horizontal
        con.rayar(matriz, linea8, 3, 2, 1);
        //vertical
        con.rayar(matriz, linea4, 5, 2, 1);

        if (con.jugar(boton8, 2, 1, matriz, jLabel7, jLabel8) == 1) {

        }
    }//GEN-LAST:event_boton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnRaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JPanel j0;
    private javax.swing.JPanel j00;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel linea1;
    private javax.swing.JLabel linea2;
    private javax.swing.JPanel linea3;
    private javax.swing.JPanel linea4;
    private javax.swing.JPanel linea5;
    private javax.swing.JPanel linea6;
    private javax.swing.JPanel linea7;
    private javax.swing.JPanel linea8;
    // End of variables declaration//GEN-END:variables
}
